export const MOCK_QUERIES = [
  { title: "Don't Ask Why", artist: "Katzù Oso" },
  { title: "Lakers Town (feat. Michael McBolton)", artist: "Joey Dosik" },
  { title: "Home", artist: "Violet Crime" },
  { title: "Blow My Cover", artist: "Ansley Stewart" },
  { title: "Future Me Hates Me - Live", artist: "The Beths" },
  { title: "You Better Run", artist: "Delta Maid" },
  { title: "No News No Blues", artist: "Paul Cherry" },
  { title: "It Will Come In Time", artist: "Benny Sings" },
  { title: "Addiction", artist: "Nina Tonji" },
  { title: "Quitting You (feat. Mandark)", artist: "Yo Lee" },
  { title: "Love Breaks Down - Extended Dancefloor Edit", artist: "PREP" },
  { title: "Scooby Doo", artist: "DaDood" },
  { title: "Jazz In My", artist: "Samuel Seo" },
  { title: "Peach", artist: "Aaron Childs" },
  {
    title: "With A Little Help From My Friends - Poppin Mix",
    artist: "Omarion",
  },
  { title: "Little Match Girl", artist: "Masiwei" },
  { title: "Rolling Back", artist: "Young Gun Silver Fox" },
  { title: "HAPPY FOR YOU", artist: "RIVER" },
  { title: "Rolling Back", artist: "Young Gun Silver Fox" },
  { title: "HAPPY FOR YOU", artist: "RIVER" },
  { title: "Downsize", artist: "Mills" },
  { title: "相約在地平街角", artist: "六艾司 Lilice" },
];
